scene_seg_model:
  ros__parameters:
    model_path: "data/models/SceneSeg_FP32-infer.onnx"
    backend: "onnxruntime"
    precision: "cpu"
    model_type: "segmentation"
    input_topic: "/sensors/video/image_raw"
    output_topic: "/autoseg/scene_seg/mask"

domain_seg_model:
  ros__parameters:
    model_path: "data/models/DomainSeg_FP32.onnx"
    backend: "onnxruntime"
    precision: "cpu"
    model_type: "segmentation"
    input_topic: "/sensors/video/image_raw"
    output_topic: "/autoseg/domain_seg/mask"